 platform :ios, '5.0'
 pod 'AFNetworking', '~> 1.1.0'
 target :uSnapTests, :exclusive => true do
     pod 'Kiwi'
 end
 target "uSnap (Integration Tests)", :exclusive => false do
     pod 'KIF', '~> 0.0.2'
 end
