// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.MapKit;

namespace iPhone_FrontEnd
{
	public partial class FindNearbyEventViewController : UIViewController
	{
		FindNearbyMapView _mapView;

		public FindNearbyEventViewController (FindNearbyMapView view) : base ()
		{
			Console.WriteLine("Breakpoint 2");

			this._mapView = view;
			this._mapView.ShowsUserLocation = true;
			view.BackButtonPressed+=OnBackButtonPressed;
			this.View = new FindNearbyView(view);
			view = null;
			Console.WriteLine("Breakpoint 3");
		}
		public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations ()
		{
			return UIInterfaceOrientationMask.All;
		}

		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			UIApplication.SharedApplication.SetStatusBarHidden(false,true);
		}
		void OnBackButtonPressed (object sender, EventArgs e)
		{
			var landingView = new LandingViewController();
			this.PresentViewController(landingView,true,()=>{this.Dispose();});

		}
		protected override void Dispose (bool disposing)
		{
			Console.WriteLine("Disposing FindNearbyEventViewController");
			this._mapView.BackButtonPressed-=OnBackButtonPressed;
			this._mapView = null;
			base.Dispose (disposing);

		}
	}
}
