// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.MapKit;

namespace iPhone_FrontEnd
{
	class FindNearbyView:UIView
	{
		FindNearbyMapView _mapView;

		public FindNearbyView (FindNearbyMapView view)
		{
			InitViews(view);
		}

		void InitViews (FindNearbyMapView view)
		{
			_mapView = view;
			this.AddSubview(_mapView);
		}
		public override void LayoutSubviews ()
		{
			var height = this.Bounds.Height;
			var width = this.Bounds.Width;
			_mapView.Frame = new System.Drawing.RectangleF(0,0,width,height);
		}
		protected override void Dispose (bool disposing)
		{
			Console.WriteLine("Disposing FindNearbyView"); 
			_mapView = null;
			base.Dispose (disposing);
		}
	}

}
