// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;

namespace iPhone_FrontEnd
{
	public partial class LandingPageViewController : UIViewController
	{
		public LandingPageViewController (IntPtr handle) : base (handle)
		{
			String fonts = "";
			List<String> fontFamilies = new List<String> (UIFont.FamilyNames);
			fontFamilies.Sort ();
			foreach (String familyName in fontFamilies) {
				foreach (String fontName in UIFont.FontNamesForFamilyName (familyName)) {
					fonts += fontName + "\n";
				}
				fonts += "\n";
			}
			Console.WriteLine (fonts);          
		}
	 	public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			EventIdField.Font = UIFont.FromName("ProximaNova-Bold",24);
		}
		partial void FindPressed (NSObject sender)
		{
			if(this.LandingPageView!=null){
				var originalLogoPosition = Logo.Frame;
				EventIdField.Frame = new System.Drawing.RectangleF(CreateButton.Frame.Location,CreateButton.Frame.Size);
				JoinButton.Frame =  new System.Drawing.RectangleF(MyEventsButton.Frame.Location,MyEventsButton.Frame.Size);
				LandingTagline.Hidden = true;
				FindButton.Hidden=true;
				CreateButton.Hidden=true;
				MyEventsButton.Hidden=true;
				InfoButton.Hidden=true;
				var originalCenter = LandingPageView.Center;
				UIView.Animate(0.5,()=>{

					LandingPageView.Center = new System.Drawing.PointF(originalCenter.X,originalCenter.Y-110);
					Logo.Frame = new System.Drawing.RectangleF(originalLogoPosition.X+26,originalLogoPosition.Y+110,217,98);
			
					EventIdField.Hidden = false;
					JoinButton.Hidden=false;
					BackButton.Hidden = false;
					FindTagline.Hidden = false;
				},()=>{



				});
			}
		}
		partial void BackPressed(NSObject sender){
			if(this.LandingPageView!=null){
				var originalLogoPosition = Logo.Frame;

				BackButton.Hidden = true;
				FindTagline.Hidden = true;
				EventIdField.Hidden = true;
				JoinButton.Hidden=true;

				var originalCenter = LandingPageView.Center;
				UIView.Animate(0.5,()=>{

					LandingPageView.Center = new System.Drawing.PointF(originalCenter.X,originalCenter.Y+110);					
					Logo.Frame = new System.Drawing.RectangleF(originalLogoPosition.X-26,originalLogoPosition.Y-110,270,122);
					LandingTagline.Hidden = false;
					FindButton.Hidden=false;
					CreateButton.Hidden=false;
					MyEventsButton.Hidden=false;
					InfoButton.Hidden=false;
				},()=>{

				

				});
			}
		}
		partial void OnJoinEditBegin(NSObject sender){
			if(this.LandingPageView!=null){

				var originalCenter = LandingPageView.Center;
				UIView.Animate(0.2,()=>{
					
					LandingPageView.Center = new System.Drawing.PointF(originalCenter.X,originalCenter.Y-50);				
				},()=>{
					
					
					
				});
			}
		}
		partial void OnJoinExit (MonoTouch.Foundation.NSObject sender)
		{
			((UITextField)sender).ResignFirstResponder();
			if(this.LandingPageView!=null){
				
				var originalCenter = LandingPageView.Center;
				UIView.Animate(0.2,()=>{
					
					LandingPageView.Center = new System.Drawing.PointF(originalCenter.X,originalCenter.Y+50);				
				},()=>{
					
					
					
				});
			}
		}

		partial void FindNearbyPressed (MonoTouch.Foundation.NSObject sender)
		{
			if(this.LandingPageView!=null){
				BackButton.Hidden = true;		
				var originalCenter = LandingPageView.Center;
				UIView.Animate(0.5,()=>{

					LandingPageView.Center = new System.Drawing.PointF(originalCenter.X,originalCenter.Y-(LandingPageView.Frame.Height));					

				},()=>{
					PerformSegue("GoToNearbyEventView",this);
					
					
				});
			}

		}
	}
}
