// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;

namespace iPhone_FrontEnd
{
	public partial class LandingPageViewController : UIViewController
	{
		public LandingPageViewController ():base()
		{
			String fonts = "";
			List<String> fontFamilies = new List<String> (UIFont.FamilyNames);
			fontFamilies.Sort ();
			foreach (String familyName in fontFamilies) {
				foreach (String fontName in UIFont.FontNamesForFamilyName (familyName)) {
					fonts += fontName + "\n";
				}
				fonts += "\n";
			}
			Console.WriteLine (fonts);          
			this.View = new LandingPageView();
		}
		public override void DidRotate (UIInterfaceOrientation fromInterfaceOrientation)
		{
			base.DidRotate (fromInterfaceOrientation);
		}
		public override bool WantsFullScreenLayout {
			get {
				return true;
			}
			set {
				base.WantsFullScreenLayout = value;
			}
		}
		public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations ()
		{
			return UIInterfaceOrientationMask.AllButUpsideDown;
		}
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}
	}
}
