// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;
using MonoTouch.CoreLocation;
using System.Linq;
using System.Diagnostics;
using MonoTouch.FacebookConnect;

namespace iPhone_FrontEnd
{
    class LoginDelegate:FBLoginViewDelegate
    {
        event EventHandler<EventArgs> ShowLoggedInUser;
        event EventHandler<EventArgs> ShowLoggedOutUser;
        event EventHandler<EventArgs> FetchUserInfo;
        public override void ShowingLoggedInUser (FBLoginView loginView)
        {
            if (ShowLoggedInUser!=null)
            {
                ShowLoggedInUser.Invoke(this, null);
            }

        }
        public override void ShowingLoggedOutUser (FBLoginView loginView)
        {
            if (ShowLoggedOutUser != null)
            {
                ShowLoggedOutUser.Invoke(this, new EventArgs());
            }
        }
        public override void FetchedUserInfo (FBLoginView loginView, FBGraphUser user)
        {
            if (FetchUserInfo != null)
            {
                FetchUserInfo.Invoke(this, new EventArgs());
            }
        }
    }

}