// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;
using MonoTouch.CoreLocation;
using System.Linq;
using System.Diagnostics;
using MonoTouch.FacebookConnect;

namespace iPhone_FrontEnd
{
	class LoginDelegate:FBLoginViewDelegate
	{
		public override void ShowingLoggedInUser (FBLoginView loginView)
		{
			Console.WriteLine ("logged in");

		}
		public override void ShowingLoggedOutUser (FBLoginView loginView)
		{
			Console.WriteLine ("logged out");
		}
		public override void FetchedUserInfo (FBLoginView loginView, FBGraphUser user)
		{
			Console.WriteLine ("found user {0}", user);
		}
	}

}