// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.MapKit;

namespace iPhone_FrontEnd
{
	public partial class NearbyEventViewController : UIViewController
	{
		MKMapView _mapView;

		public NearbyEventViewController (MKMapView view) : base ()
		{
			this._mapView = view;
			this._mapView.ShowsUserLocation = true;
			this.View = view;
		}
	}
}
