// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace iPhone_FrontEnd
{
	public partial class NearbyEventViewController : UIViewController
	{
		public NearbyEventViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
