// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.AssetsLibrary;
using MonoTouch.CoreGraphics;
using System.Drawing;
using System.IO;

namespace iPhone_FrontEnd
{
	class StreamTableData:UITableViewDataSource
	{

		public override int NumberOfSections (UITableView tableView)
		{
			return 1;
		}
		public override int RowsInSection (UITableView tableView, int section)
		{
			return 3;
		}
		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell(@"PhotoCell");
			if (cell == null) {
				cell = new EventPhotoCell(@"PhotoCell");
				cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			}
			return cell;
		}

	}


}
